from enum import Enum


class ErrorCode(str, Enum):
    """全局统一错误码

    格式：领域_语义，避免 Controller 内联重复定义。
    """

    # 通用
    OPERATION_FAILED = "OPERATION_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"

    # 数据源领域
    DATASOURCE_NOT_FOUND = "DATASOURCE_NOT_FOUND"
    DATASOURCE_ALREADY_EXISTS = "DATASOURCE_ALREADY_EXISTS"
    DATASOURCE_NOT_CONNECTED = "DATASOURCE_NOT_CONNECTED"
    CONNECTION_TEST_FAILED = "CONNECTION_TEST_FAILED"

    # Token 领域
    TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
